### ISSUE TITLE
Regression in segment time calculation - presentationTimeOffset is added when it should not be

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1232]
https://github.com/google/shaka-player/commit/20750504fecd4855f2997dcd2eb92a7024dc2bdc appears to have introduced a regression, with the key line in question being https://github.com/google/shaka-player/blame/master/lib/dash/segment_template.js#L324. Possibly more of the logic is suspect - I did not dig deeper beyond finding why the first numbers with my video were off.

As far as I can tell, the function `find` appears to be there to determine the ~MPD start time in seconds~ segment position of the segment containing `periodTime`, which is an offset from the start of the period in seconds.

Using `presentationTimeOffset` in this calculation is incorrect. PTO does not determine anything about the MPD timeline, it says what media timestamp (PTS) corresponds to periodTime = 0. You should only use it for aligning the media timeline with the MPD timeline.

The referenced commit causes any segmentTemplate-using streams with presentationTimeOffset to have segments scheduled at the wrong moments in time.

Still working on getting playable URL for you but I thought I would post immediately as it seemed pretty clear cut to me. Let me know if you want more supporting material and evidence and I am happy to provide.

Example MPD:

```
<MPD type="dynamic" availabilityStartTime="1970-01-01T00:07:00Z" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264" timeShiftBufferDepth="PT15M" minimumUpdatePeriod="PT15S" minBufferTime="PT2S" publishTime="2018-01-17T14:49:04.237755Z" xmlns="urn:mpeg:dash:schema:mpd:2011">
  <!--availabilityStartTime is adjusted to add a delay of 00:07:00 to the availability timeline compared to the authoring timeline. Timestamps in period/segment paths indicate authoring time (UTC), not availability time (UTC+delay). Playback uses availability time.-->
  <Period id="p_1516198946762" start="P17548DT14H22M26.762S">
    <!--Starts 2018-01-17 14:21:59.762Z (1,516,198,946,762 ms from epoch) on the authoring timeline.-->
    <!--Starts 2018-01-17 14:28:59.762Z (1,516,199,366,762 ms from epoch) on the availability timeline.-->
    <AdaptationSet segmentAlignment="true" group="1">
      <SegmentTemplate timescale="1000" duration="4000" media="p_1516198946762/$RepresentationID$/$Number%06d$.m4s" initialization="p_1516198946762/$RepresentationID$/init.mp4" presentationTimeOffset="1516198946762" />
      <Representation id="Track0" mimeType="audio/mp4" startsWithSAP="1" bandwidth="64000" audioSamplingRate="48000" codecs="mp4a.40.2" />
    </AdaptationSet>
    <AdaptationSet segmentAlignment="true" group="2" par="16:9" maxHeight="720" maxWidth="1280" frameRate="30">
      <SegmentTemplate timescale="1000" duration="4000" media="p_1516198946762/$RepresentationID$/$Number%06d$.m4s" initialization="p_1516198946762/$RepresentationID$/init.mp4" presentationTimeOffset="1516198946762" />
      <Representation id="Track1" mimeType="video/mp4" startsWithSAP="1" bandwidth="3000000" sar="1:1" width="1280" height="720" codecs="avc1.640032" />
    </AdaptationSet>
  </Period>
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014" value="Manifest.mpd" />
</MPD>
```

The period starts at some point on 2018-01-17. Both the MPD timeline zero point and the media timeline zero point are in 1970. The latter is indicated by presentationTimeOffset. The first segment to be played at period start is number 1.

However, because of the problematic commit, Shaka adds PTO to the first segment, trying to play back something from 2066 instead (it tries to play segment number 379054268 as I post this).

**Comment by sandersaares** [comment]
Here's an externally accessible URL from a development server: https://live.axtest.net/routes/lapd-v1-cb/www_c1/Manifest.mpd

I expect it will stay up for around 6-7 hours from this comment. After that it might stop publishing the period with presentationTimeOffset due to a known issue.

**Comment by sandersaares** [comment]
This is breaking a lot of streams. Can we get a fix in the near future @joeyparrish? We're currently not able to upgrade to latest version due to this blocking us.

**Comment by stroemlund** [comment]
We have a problem where shaka 2.3.1 want start playing our streams however dashif, bitmovin and older shaka versions starts playing the mpeg dash streams immediately Shaka keeps saying there is an issue with the time of the segments however all other players are playing back our streams just fine. Could these issues be related? I can provide a test url for any of the devs if wanted. Just can't post it public.

**Comment by joeyparrish** [comment]
This should be working now in the nightly build:  https://nightly-dot-shaka-player-demo.appspot.com/demo/

Can someone please confirm?

**Comment by stroemlund** [comment]
Doesn’t work for me. My stream still shows the same problems as before.

Jacob

**Comment by joeyparrish** [comment]
@TheModMaker, can you please take a look?

**Comment by sandersaares** [comment]
I confirm the stream I posted appears to work with the nightly build.

**Comment by TheModMaker** [comment]
@stroemlund Can you give us a manifest URL?

**Comment by stroemlund** [comment]
https://dmpe12-4dash.akamaized.net/dash/live/594304/DPME12-4/index.mpd

**Comment by TheModMaker** [comment]
@stroemlund  That manifest doesn't use `presentationTimeOffset`, so the issue is unrelated.

When I fetch the manifest at `2018-02-01T17:50:49Z`, the `availabilityStartTime` is `2018-01-29T07:43:30Z`, which puts the live edge at 295639 seconds.  The first segment in the manifest is at `26610480000 / 90000` or 295672 seconds, which is in the future.  It looks like your stream is suffering from drift.  See #999.

Since this is unrelated I'm closing the issue.  If you have problems with another stream, you should probably file a new issue.

**Comment by stroemlund** [comment]
Sure makes sense! Well we are running elemental encoders according to standards and we see no reason for it to drift as this is a problem even at the very first segment of the stream. So it doesn’t happen over time but immediately from the start.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.3.  The correctness of the fix was still being debated while I was preparing v2.3.2.  Sorry for any inconvenience caused by delaying this fix for one more release.

**Comment by stroemlund** [comment]
So 2.3.3 the drift fix should be included?

**Comment by TheModMaker** [comment]
No, we are still working on fixes for drift, which you can fallow in #999.  The fix for `SegmentTemplate` with duration will appear in 2.3.3.

**Comment by stroemlund** [comment]
Just funny the streams are playing in 2.2.x

**Comment by joeyparrish** [comment]
Referring to the analysis above in https://github.com/google/shaka-player/issues/1232#issuecomment-362349850, if the segment times are in the future, it sounds like it's not drift, but rather a clock sync or encoder clock issue.  Is the clock on your encoder correct?  Do you have clock sync set up on the content?

**Comment by stroemlund** [comment]
The clock is spot on. And how can the same encoder set different time on segments and manifest start?

**Comment by joeyparrish** [comment]
I don't know, but it could be a bug in the Elemental encoder.  Have you talked to Elemental support?

**Comment by stroemlund** [comment]
Yes plenty of times. And they simply refers to the stream working in every other players except shaka due to shaka handling the timestamps differently.

**Comment by joeyparrish** [comment]
As far as we can tell ([analysis above](https://github.com/google/shaka-player/issues/1232#issuecomment-362349850)), the segment times are in the future.  Since we are already planning a general approach to ignore availabilityStartTime (#999), I don't think there's anything more specific we can do for you right now.  I expect your problem will be solved once #999 is implemented.  In the mean time, you are always welcome to customize Shaka Player sources however you need to for your deployment.

Sorry we couldn't do more for you directly.  If you subscribe to #999, you will be notified when we close the issue.
