### ISSUE TITLE
Live, multi-period DASH, Shaka makes thousands of requests for the same segments

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1464]
(Updated 6/15 with results from some additional testing)
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
This is reproducible in 2.3.9 and 2.4.1, and master

**Can you reproduce the issue with our latest release version?**:
This is not reproducible in 2.3.8 or 2.4.0.

**Can you reproduce the issue with the latest code from `master`?**:
Yes, I can reliably reproduce in master.

**Are you using the demo app or your own custom app?**:
Custom app

**If custom app, can you reproduce the issue using our demo app?**:
No

**What browser and OS are you using?**:
Chrome 67 macOS

**What are the manifest and license server URIs?**:
Sent a curl by email to obtain manifest url. Unfortunately it's not practical to share a license since there is a custom authorization flow.

**What did you do?**
Load multi-period live DASH stream with Shaka

**What did you expect to happen?**
If a request is successful, Shaka should not re-request the same segment.

**What actually happened?**
Shaka made thousands of requests for the same segments, in quick succession. Chrome network panel indicated HTTP status 200 (from disk cache) on subsequent requests for the same segment. See attachment below, which shows requests made after a few minutes of playback. It's hard to troubleshoot because DevTools becomes virtually unusable. Also note that I forced Shaka to use http_xhr_plugin to see if it was a problem with Fetch. I was able to reproduce using both plugins.

During this time, the player appears to go in and out of buffering states. It seems to recover at some point (it stops requesting the same segment over and over). Then playback proceeds. Then there is a period of buffering, and then playback proceeds again. Then it reaches a point where it makes several thousand more requests for the same segment, and goes through the whole process again.

This only appears to happen with live, multi-period content. This manifest comes from our ad provider, YoSpace. I was not able to reproduce with VOD or our regular single-period content. (For comparison, this manifest works as expected: https://dfwlive-sponsored.akamaized.net/Content/DASH.abre/Live/channel(CNNHD-8249.dfw.1080)/manifest_mobile.mpd)

For what it's worth I've only seen this happen with audio segments so far.  That might be a coincidence. The behaviour looks like Shaka got stuck in a loop with a poorly defined exit condition. I will continue troubleshooting to see if I can learn more. Any ideas in the meantime?

**Edit:** appears to be caused by https://github.com/google/shaka-player/commit/b212ef9b4f1fa7ff843912e9919c37a5c003fe12

![shaka_thousands_requests](https://user-images.githubusercontent.com/7190265/41375600-8d761ba4-6f24-11e8-8c86-53ab8f825256.png)

**Comment by chrisfillmore** [comment]
I tested in 2.4.1 today and can reproduce with that version.

**Comment by chrisfillmore** [comment]
This appears to be caused by https://github.com/google/shaka-player/commit/b212ef9b4f1fa7ff843912e9919c37a5c003fe12. If I revert this change, the problem goes away.

Still investigating...

**Comment by chrisfillmore** [comment]
Just to confirm the above, I've tested and can reproduce in 2.3.9, as well as 2.4.1.
2.3.8 and 2.4.0 do not have this problem.

**Comment by chrisfillmore** [comment]
I've sent an email to shaka-player-issues with a curl you can use to get a manifest url.

**Comment by chrisfillmore** [comment]
I have only ever seen this happen so far with audio segments. A sample manifest is attached. One thing I notice is that we have three AdaptationSet for audio in each Period, each AdaptationSet has one Representation. I'm not sure why we don't just have one AdaptationSet with three Representation, or if that would be functionally the same thing.

[sample_multi_period.txt](https://github.com/google/shaka-player/files/2106707/sample_multi_period.txt)

**Comment by chrisfillmore** [comment]
StreamingEngine gets into a loop of scheduling updates every 0s. This is the V2 logging output:

```
(audio:10484) updating in 0 seconds
streaming_engine.js:1533 (audio:10484) finished fetch and append
streaming_engine.js:1160 (audio:10484) timeNeeded=338513.9650917
streaming_engine.js:1171 (audio:10484) update_: playheadTime=338509.416251 bufferedAhead=4.5498399999924
streaming_engine.js:1322 (audio:10484) next position known: position=10
streaming_engine.js:1467 (audio:10484) fetchAndAppend_: playheadTime=338509.416251 currentPeriod.startTime=338459.755 reference.position=9 reference.startTime=48.1940917 reference.endTime=54.2100917
streaming_engine.js:1503 (audio:10484) fetching segment
streaming_engine.js:2151 fetching: reference=[object Object]
simple_abr_manager.js:181 Segment downloaded: deltaTimeMs=5 numBytes=73869 lastTimeChosenMs=1529086691745 enabled=true
simple_abr_manager.js:229 Suggesting Streams...
simple_abr_manager.js:245 Still within switch interval...
mp4_parser.js:184 Parsing MP4 box styp
mp4_parser.js:184 Parsing MP4 box sidx
mp4_parser.js:184 Parsing MP4 box prft
mp4_parser.js:184 Parsing MP4 box moof
mp4_parser.js:184 Parsing MP4 box mdat
streaming_engine.js:1822 (audio:10484) checking buffer length
streaming_engine.js:1852 (audio:10484) buffer behind too large: playheadTime=338509.416251 bufferedBehind=30.01016000000527 bufferBehind=30 overflow=0.010160000005271286
streaming_engine.js:1862 (audio:10484) evicted 0.010160000005271286 seconds
streaming_engine.js:1745 (audio:10484) appending media segment
streaming_engine.js:1751 (audio:10484) appended media segment
```

**Comment by chrisfillmore** [comment]
I think I will put together a simple demo app that I can send over to Shaka team to repro this issue. But that will not happen this week, and I'm on vacation next week, so I likely won't return to this issue until ~Jul 4 at the earliest.

**Comment by TheModMaker** [comment]
I think it would be much easier with a self-contained repro.  Not having a license server makes repro-ing and fixing this hard.  So we'll probably be waiting until you send us a repro.  One thing you could try is removing [this bit](https://github.com/google/shaka-player/blob/master/lib/media/segment_index.js#L289-L299) in the SegmentIndex.  I think it is causing duplicate index entries and confusing streaming.

**Comment by TheModMaker** [comment]
I just pushed a change that will probably fix your issue.  Could you retry from `master` or with the latest nightly site?  <https://nightly-dot-shaka-player-demo.appspot.com/demo/>

**Comment by chrisfillmore** [comment]
The fix seems to be good. So far I haven't seen it get into making thousands of requests like it was before. However, I do still see it periodically request a segment a second time. Here I've sorted the requests in the Network tab by name:

<img width="859" alt="screen shot 2018-07-10 at 9 08 38 pm" src="https://user-images.githubusercontent.com/7190265/42545373-7d788220-8485-11e8-8ec7-23eb0728c196.png">

<img width="909" alt="screen shot 2018-07-10 at 8 36 40 pm" src="https://user-images.githubusercontent.com/7190265/42545333-4c2a4e60-8485-11e8-9e82-b0fe006f5d2f.png">

The behaviour does not disrupt playback, but is there any reason why Shaka should request a segment twice?

**Comment by chrisfillmore** [comment]
I consider this issue resolved. I will file a new issue for the duplicate requests if I have an issue with it. Thanks.
