### ISSUE TITLE
Bad subtitle rendering 

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2334]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**What version of Shaka Player are you using?** 2.5.7

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Chrome 79 macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

I can send the stream if necessary, but I have attached the ttml file that fails.

**What did you do?**

Load a stream

**What did you expect to happen?**
Subtitles are rendering correctly

**What actually happened?**

Bad subtitle rendering in 2.5.7
![2 5 7](https://user-images.githubusercontent.com/8983024/72077931-68d09600-32f8-11ea-9c1c-a2930cf41a68.png)

Rendering in 2.5.6
![2 5 6](https://user-images.githubusercontent.com/8983024/72077946-6f5f0d80-32f8-11ea-9920-9cccea3cbda5.png)

Rendering in Dash.js 3.0.0
![dashjs](https://user-images.githubusercontent.com/8983024/72077967-7be36600-32f8-11ea-9033-29cd1549a7b9.png)

TTML file

```
<?xml version="1.0" encoding="UTF-8"?>
<tt ttp:cellResolution="50 30" ttp:timeBase="media" xml:lang="en" xmlns="http://www.w3.org/ns/ttml" xmlns:ebutts="urn:ebu:tt:style" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <head>
    <styling>
      <style ebutts:linePadding="0.5c" tts:color="#ffffff" tts:fontFamily="monospace" tts:fontSize="125%" tts:fontStyle="normal" tts:lineHeight="normal" tts:textAlign="center" tts:wrapOption="noWrap" xml:id="paragraphStyle"/>
      <style tts:backgroundColor="#000000" tts:color="#ffffff" xml:id="textStyle"/>
    </styling>
    <layout>
      <region tts:displayAlign="after" tts:extent="80% 80%" tts:origin="10% 10%" tts:overflow="visible" xml:id="speaker"/>
    </layout>
  </head>
  <body style="paragraphStyle">
    <div region="speaker">
      <!-- text-based TTML -->
      <p begin="00:47:16.954" end="00:47:18.622" xml:id="s0">
        <span style="textStyle">¿Dónde están los demás?</span>
      </p>
      <p begin="00:47:19.690" end="00:47:20.089" xml:id="s1">
        <span style="textStyle">Seguro están muertos.
          <br/>
          Solo quedamos tú y yo.</span>
      </p>
    </div>
  </body>
</tt>
```

Note the error occur with the commit https://github.com/google/shaka-player/commit/5e09ffc9d4b803ad92db7af877110be84edd36d0

**Comment by theodab** [comment]
I had thought that that was the behavior the spec was mandating, and that Dash.js was doing it wrong. In the examples in the spec the element's size seems to be defined by `tts:extent` (see the illustration in the [section on extent](https://www.w3.org/TR/ttml1/#style-attribute-extent)).
But I might be wrong, or we might be ignoring some other rules that I missed. I'm not all that confident in my reading of the spec.

**Comment by joeyparrish** [comment]
It seems that we're misinterpretting the region & background.  We are taking the background color from the styles and the size and position of the region and combining them all into one thing to display.

Using [this IMSC1 test renderer](http://sandflow.com/imsc1_1/index.html), I am able to see the differences and play with various parameters to see how they should be rendered.

**Comment by joeyparrish** [comment]
@avelad, can you please send test content for this so we can know for sure when we've fixed it?

**Comment by avelad** [comment]
Yes, you can use: https://livesim.dashif.org/dash/vod/testpic_2s/multi_subs.mpd

Use English track that uses TTML.

DASH IF Player:
![dashif](https://user-images.githubusercontent.com/8983024/73051204-7d796600-3e82-11ea-854c-211bee02a067.png)

Shaka Player:
![shaka](https://user-images.githubusercontent.com/8983024/73051239-9255f980-3e82-11ea-8cab-33141b427968.png)

**Comment by mhosman** [comment]
Still happening in CAF Player (Chromecast) using Shaka Player 2.5.8 (see changelog):

> March 12, 2020
> CAF Receiver
> 
> Added new device capability IS_CBCS_SUPPORTED to deviceCapabilities.
> Upgraded Shaka Player to 2.5.8.

**Comment by joeyparrish** [comment]
The fix hasn't made it into CAF yet.  The fix has been cherry-picked and will appear in Shaka Player v2.5.10.  We don't control the CAF release schedule, but will notify the Cast team.

**Comment by mhosman** [comment]
Ok, it will be great if you can notify to the cast team because CAF player does not have the availability to downgrade. Thanks @joeyparrish!

**Comment by mhosman** [comment]
Hey @joeyparrish since this issue is still not fixed in CAF player, there's a workaround? Thanks!!

**Comment by joeyparrish** [comment]
We are finishing the v2.5.10 release of Shaka Player right now.  I expect it to be released this week.  I don't know how the CAF test & release schedule may be impacted by the Coronavirus pandemic right now, but it's possible that things may take longer than usual.

I don't have a workaround for CAF, unfortunately.  You may wish to file a support request with the Cast team about that.  They could advise you better than we could.

**Comment by joeyparrish** [comment]
@mhosman, I had a conversation with the Cast team this morning, and we discussed this fix specifically.  What we realized on closer review was that the fix for this issue is entirely in our UI, which CAF does not use.

Subtitle rendering in CAF is done through native browser APIs (`VTTCue` specifically).  This means that some positioning and formatting styles are lost, either because `VTTCue` doesn't have an equivalent or because some parts of `VTTCue` are unimplemented by the browser.

Given that this fix and the original bug were both part of our UI, I suspect your subtitle rendering issue in CAF is distinct from this issue.  If you'd like to file a separate bug and give content links and screenshots, we can look into it.  The `VTTCue`-based rendering that CAF uses can be easily reproduced in desktop Chrome, as well, by disabling the Shaka Player UI in our demo app.

Thanks!
