### ISSUE TITLE
CEA-608 captions are garbled

### ISSUE THREAD

**Issue by ppatlolla-turner** [google/shaka-player#2395]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Didn't try

**Are you using the demo app or your own custom app?**
Using the demo app.
https://shaka-player-demo.appspot.com/demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome - Version 80.0.3987.100 (Official Build) (64-bit)
OS - macOS 10.14.6 (18G2022)
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Roku, Apple TV and alternate HTML5 players do display the captions correctly. 

**What are the manifest and license server URIs?**
Will send the manifest and license server url via email with bug number in the subject line.
**What did you do?**
Played the stream sent via email by populating  the Custom Content button. 

**What did you expect to happen?**
608 captions should have been displayed accurately. 

**What actually happened?**
<img width="1217" alt="608 garbled via Shaka on Chrome - 1" src="https://user-images.githubusercontent.com/22914181/74466576-56dc9880-4e4c-11ea-8ccc-c1f0c8c09a46.png">

<img width="713" alt="608 garbled via Shaka on Chrome - 2" src="https://user-images.githubusercontent.com/22914181/74465899-16304f80-4e4b-11ea-95b4-e29ff3def517.png">

<img width="707" alt="Screen Shot 2020-02-13 at 11 08 27 AM" src="https://user-images.githubusercontent.com/22914181/74472436-c8b9df80-4e56-11ea-9b75-d958b92ce021.png">

**Comment by joeyparrish** [comment]
@ppatlolla-turner, are those captions meant to be in English?  Can you share a screenshot of the same text being rendered correctly in another player, for reference?

**Comment by ppatlolla-turner** [comment]
Yes, the captions are meant to be in English.
Shaka player via HLS manifest does identity the captions as English. Shaka player doesn’t identity the captions as English when DASH manifest is used.

Attached screen-shot displaying the captions correctly.

Thanks
Pramod

**Comment by MilosRasic** [comment]
![EBdS-1uWkAEO6YF](https://user-images.githubusercontent.com/533052/74469391-db570780-4e9c-11ea-86dd-e8981c16c86e.jpg)

**Comment by TheModMaker** [comment]
I confirmed the captions are displayed weirdly.  We don't do the caption parsing ourselves, we use [mux.js](https://github.com/videojs/mux.js), so it is probably a bug with them.  I notice nothing obviously wrong with your MP4 files.

**Comment by joeyparrish** [comment]
@TheModMaker, please try the latest mux.js release and mux.js master to see if this is already fixed upstream.  I've seen a lot of PRs landing in mux lately.

**Comment by TheModMaker** [comment]
It still reproduces with both the latest release and their `master`.

**Comment by joeyparrish** [comment]
Because the stream is encrypted, it's possible that the CC data is garbled the encryption.  Decryption happens inside the browser, but CC parsing is happening in JavaScript.  JavaScript apps have no access to the keys or the decrypted media.

It could still be a bug in the parser of mux.js, but at the moment, I have no way to verify whether or not the caption data was encrypted.

So, some questions for @ppatlolla-turner:

1. Do you have another web-based player that correctly displays these captions?  If so, which one?
2. What software was used to package the media?
3. Are you certain the CC data was left in the clear during encryption?
4. Can you try a clear version of the same stream and see if that makes a difference?

Thanks!

**Comment by joeyparrish** [comment]
Just got some technical details from a colleague:

> CEA608 is embedded in H264 SEI NALU.  For packagers that follow CENCv3 specification, SEI is not encrypted.  If they follow CENCv1 specification, SEI is encrypted.

**Comment by ppatlolla-turner** [comment]
CEA608 captions do break even when clear streams are used. Sending details via email.

**Comment by joeyparrish** [comment]
Perfect, thank you.  I'm sure that will help.

**Comment by joeyparrish** [comment]
With your permission, I'd like to send a single encrypted segment along with its corresponding init segment in a bug report upstream to [mux.js](https://github.com/videojs/mux.js), which we use for CEA parsing.  I would be attaching those individual segments publicly in a public report, without their original URLs, their keys, or their license server URLs.

Do I have your permission to send those two segments publicly to mux.js?

**Comment by ppatlolla-turner** [comment]
Yes you do have permission to share. Captions start at 15 seconds into the stream. 
Better to send first 4 segments (4 x 6.006 seconds).

**Comment by joeyparrish** [comment]
So far, the mux.js team doesn't know what is wrong with their CEA parser on this content, and neither do we.

If you have access to an open-source CEA parser in any language that works with this content, we could compare it with mux.js and see if we can identify the issue.

In the mean time, while we wait on either the mux.js team to provide a resolution or a working CEA parser to compare with, we will have to remove this issue from the v2.6 milestone.

We apologize for the inconvenience.

**Comment by joeyparrish** [comment]
After some more digging, I have determined that this is definitely caused by b-frames in the content.  Mux.js does not currently support b-frames correctly when extracting captions.  Re-encoding without b-frames fixes the extraction.  See https://github.com/videojs/mux.js/issues/332#issuecomment-622988104 for details.

**Comment by ppatlolla-turner** [comment]
Thanks for the update. 
As an alternate plan we are exploring webVTT. If we need to use 608 for captions we now know that we need to remove b-frames from the video. Removing b-frames is very unlikely. 
Hope mux.js supports b-frames for 608.

**Comment by joeyparrish** [comment]
It turns out to be related to the correct parsing of `trun` boxes in mux.js.  The v1 boxes have signed ints for composition time offset, while v0 has unsigned ints.  mux.js was only correctly parsing v0 boxes.  I have a PR for mux.js up for review that fixes the issue: https://github.com/videojs/mux.js/pull/338

Thanks to our colleagues on the Cast team for pointing out the root cause!

**Comment by ppatlolla-turner** [comment]
Confirming that 608 captions have been fixed.

<img width="1074" alt="608 after fix" src="https://user-images.githubusercontent.com/22914181/82219005-91355600-98d1-11ea-8993-cb5a2699d633.png">
