### ISSUE TITLE
Dynamic stream with SegmentTemplate hangs up after update

### ISSUE THREAD

**Issue by mad-gooze** [google/shaka-player#2983]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.17, 3.0.5
**Can you reproduce the issue with our latest release version?**
Yes
**Can you reproduce the issue with the latest code from `master`?**
Yes
**Are you using the demo app or your own custom app?**
Both
**If custom app, can you reproduce the issue using our demo app?**
Yes
**What browser and OS are you using?**
Latest Chome, macos, seems to be non platfrom related

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-
**What are the manifest and license server URIs?**

https://strm.yandex.ru/kal/sibir/manifest.mpd?dvr=180

**What did you do?**
- Start video
- Suspend or pause js execution for 3 minutes
- Return to tab

You can also stub first manifest request with an expired one https://pastebin.com/XbBdrVts (publishTime="2020-11-11T17:22:10Z") and use not stubbed requests for later updates.

**What did you expect to happen?**
Playback continues, timeline gets re-created to match updated manifest

**What actually happened?**
Playback stalls

I've check this case in dash.js and it's working. Looks like not overlapping manifest updates are broken in shaka. Maybe I am missing some configurable logic that can overcome this problem?

**Comment by joeyparrish** [comment]
I'm unable to reproduce this issue in v3.0.8, so I presume we have already fixed it.  I watched the stream through several manifest updates.  I'm going to close the issue for now.

If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!

**Comment by mad-gooze** [comment]
@shaka-bot reopen

**Comment by mad-gooze** [comment]
@joeyparrish I still reproduce on 3.0.8 if I start playback with stubbed manifest from  https://pastebin.com/XbBdrVts and switch to actual manifest from https://strm.yandex.ru/kal/sibir/manifest.mpd?dvr=180

**Comment by TheModMaker** [comment]
One problem I notice is your stubbed manifest has a different value for `availabilityStartTime`.  It only differs by 10 seconds, but this could be causing problems with streaming.  This attribute cannot change during playback.  Does it work if you set the `streaming.jumpLargeGaps` configuration to `true`?  Does the stream recover if you seek?
