### ISSUE TITLE
selectAudioLanguage with a "role" doesn't immediately select correct audio track

### ISSUE THREAD

**Issue by bhh1988** [google/shaka-player#948]
This bug can be reproduced only if there are audio tracks with the same language, but different roles. Selecting a new audio track is effectively a no-op. Stepping through the code, this is due to a bug in chooseStreams_() in player.js, which only checks for if language has changed between the selected and currently active track, when deciding whether to actually switch tracks or not (it does look like it's setting the correct list of variants for ABR though, since 40121946957c8ff68ba13e4ea00fe0bc592a88ab for #767 , so I believe ABR would eventually set the desired audio track eventually).

**Comment by joeyparrish** [comment]
@bhh1988, I believe this may have been fixed in the refactor in 7e0f469. Would you be willing to retest?

**Comment by bhh1988** [comment]
Yes this seems to be fixed now. Thanks!

**Comment by bhh1988** [comment]
I realize this issue still exists in 2.1.6. Makes sense because https://github.com/google/shaka-player/commit/7e0f46931e122859d57ef0507143f3ebd4d604d5 isn't on that branch yet. Is there a plan to backport the fix?

**Comment by joeyparrish** [comment]
Backporting is not trivial, because the refactor touched some external interfaces.  We can't change the AbrManager API mid-2.1.x.

I'm looking into other solutions, including a partial reimplementation.

**Comment by joeyparrish** [comment]
Fixed for v2.1.7.  Thanks!
