### ISSUE TITLE
Airplay + Fairplay not working on iOS/macOS 26.1

### ISSUE THREAD

**Issue by multiplexer2** [google/shaka-player#9491]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

4.16.11

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari on iOS/macOS 26.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

The problem can be reproduced with Fairplay videos on the Shaka demo page.

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

The problem can be reproduced with Fairplay videos on the Shaka demo page.

**What did you do?**

- Navigate to the Shaka demo page and filter for Fairplay DRM content.
- Play a video. e.g. Tears of Steel (HLS AVC - FairPlay - SingleKey)
- The video should start playing without issues
- Start Airplay against an Apple TV or other Airplay-device

**What did you expect to happen?**
The video to play nicely with Airplay

**What actually happened?**

- The Airplay playback never starts, and the following error message is displayed on the page:

> [Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (The operation is not supported.,NotSupportedError: The operation is not supported.,)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6006)

- Error message in console:

> category: 6
> code: 6006
> data: ["The operation is not supported.", NotSupportedError: The operation is not supported., undefined] (3)
> handled: false
> message: "Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (The operation is not supported.,NotSupportedError: The operation is not supported.,)"
> severity: 2
> stack: "@https://shaka-player-demo.appspot.com/lib/util/error.js:101:24↵@https://shaka-player-demo.appspot.com/lib/drm/drm_engine.js:1335:41"

**Are you planning to send a PR to fix it?**

No

**Comment by multiplexer2** [comment]
It seems like this only happens when using the modern EME, not when using legacy Apple Media Keys.

**Comment by avelad** [comment]
@robwalch, Do you know of any internal errors related to this?

**Comment by avelad** [comment]
I reproduced it, so the error is in Safari 26.1 itself; it's not something we can fix in Shaka. Sorry!

**Comment by avelad** [comment]
Same issue on iOS 26.2

**Comment by avelad** [comment]
@jyavenard Do you know if this is a known issue in Safari?

Note: It seems like this only happens when using the modern EME, not when using legacy Apple Media Keys.

**Comment by flpymonkey** [comment]
I was able to work around this issue using the legacy Apple Media Keys as described [here](https://github.com/shaka-project/shaka-player/blob/main/docs/tutorials/fairplay.md)

**Comment by avelad** [comment]
Maybe related to https://github.com/WebKit/WebKit/pull/57064

**Comment by avelad** [comment]
Fixed on 26.2.1.

**Comment by lorenzo-fsp** [comment]
> Fixed on 26.2.1.

@avelad Hello, how did you test this? We tried with 26.3 and the EME keys still don't work
